name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos12:
    runs-on: macos-12

    strategy:
      matrix:
        xcode: ["14.2.0", "13.4.1"]

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: swift test

  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        swift: ["5.7.3", "5.6.3", "5.5.3"]

    container:
      image: swift:${{ matrix.swift }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install System Dependencies
        run: |
          apt-get update
          apt-get install -y libxml2-dev
      - name: Build and Test
        run: swift test
